# Generated by Django 3.1 on 2021-08-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_auto_20210823_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Personas.persontype'),
        ),
    ]
